Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/app/core/tokenhub.py", line 40, in run
    self.client.send(b'### INCOMING DATA:\n\n')
BrokenPipeError: [Errno 32] Broken pipe

Exception in thread Thread-41:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/app/core/tokenhub.py", line 40, in run
    self.client.send(b'### INCOMING DATA:\n\n')
BrokenPipeError: [Errno 32] Broken pipe

Exception in thread Thread-101:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/app/core/tokenhub.py", line 40, in run
    self.client.send(b'### INCOMING DATA:\n\n')
BrokenPipeError: [Errno 32] Broken pipe

Exception in thread Thread-142:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/app/core/tokenhub.py", line 40, in run
    self.client.send(b'### INCOMING DATA:\n\n')
BrokenPipeError: [Errno 32] Broken pipe

^[[AException in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/app/core/tokenhub.py", line 40, in run
    self.client.send(b'### INCOMING DATA:\n\n')
BrokenPipeError: [Errno 32] Broken pipe

Exception in thread Thread-36:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/app/core/tokenhub.py", line 40, in run
    self.client.send(b'### INCOMING DATA:\n\n')
BrokenPipeError: [Errno 32] Broken pipe

